version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "inventory-tracker-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19hrnsfhg5439"
s3_prefix = "inventory-tracker-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
